name: Generate ASCII Artwork

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2

            - name: List and read files
              run: ls -ltra

            - name: Executing shell script
              run: ./ascii-script.sh