name: Exploring variables and secrets
on:
  workflow_dispatch
      
env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: trackercanada
    IMAGENAME: github-actions-nqinx

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Docker Build
              run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGENAME:latest

            - name: Docker Login
              run: echo docker login --username=$DOCKER_USERNAME --password=${{ secrets.DOCKER_PASSWORD }}

            - name: Docker Publish
              run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGENAME:latest

    deploy:
        if: github.ref == 'refs/head/main'
        runs-on: ubuntu-latest
        needs: docker
        concurrency:
          group: production-deployment
          cancel-in-progress: true
        steps:
            - name: Docker run
              run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGENAME:latest

            - name: Sleep
              run: sleep 60              

            